version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - nginx_conf:/etc/nginx/conf.d:z
    networks:
      - sonarnet
    restart: always

  database:
    image: postgres:10
    container_name: postgresql
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=sonarqube
    volumes:
      - postgresql_data:/var/lib/postgresql:z

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    hostname: sonarqube
    networks:
      - sonarnet
    depends_on:
      - database
    ports:
      - 9000:9000
    environment:
      - sonar.jdbc.url=jdbc:postgresql://database:5432/sonarqube
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf:z
      - sonarqube_extensions_plugins:/opt/sonarqube/extensions/plugins:z
      - sonarqube_extensions_downloads:/opt/sonarqube/extensions/downloads:z
      - sonarqube_data:/opt/sonarqube/data:z

networks:
  sonarnet:
    driver: bridge

volumes:
  nginx_conf:
  postgresql_data:
  sonarqube_conf:
  sonarqube_extensions_plugins:
  sonarqube_extensions_downloads:
  sonarqube_data:
